title: Londonche – Bulgarian Children's choir
description: A choir for children to sing traditional Bulgarian songs, based in London

# remote_theme: pages-themes/slate@v0.2.0
remote_theme: mmistakes/minimal-mistakes@4.24.0
plugins:
- jekyll-remote-theme #
